version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0
      - image: cimg/android:2021.08.01 # Updated to a correct version tag
    environment:
      JVM_OPTS: -Xmx2048m
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm run test

      - run:
          name: Make Debug Build
          working_directory: ~/repo/android
          command: ./gradlew assembleDebug

      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: debug-apks
