version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Yarn Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: dependency-cache-{{ runner.os }}-{{ checksum "yarn.lock" }}

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Move to Android Directory
        run: cd android

      # Add the Android build steps below this line
      - name: Build Android Debug APK
        run: |
          # Use the correct path to the Gradle wrapper script (gradlew) in your project
          ./gradlew assembleDebug

      # Add any additional steps or post-build actions as needed
