version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0
    environment:
      JVM_OPTS: -Xmx2048m
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Move to Android Directory
          command: cd android
      - run:
          name: Make Debug Build
          working_directory: ~/repo/android
          command: ./gradlew assembleDebug
