version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Yarn Cache
        run: |
          yarn install
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Move to Android Directory
        run: cd android

      - name: Make Debug Build
        run: ./gradlew assembleDebug

  create-debug-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use a version of Node.js that is compatible with your project

      - name: Install Dependencies
        run: npm install

      - name: Set up Android
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17' # Use a version of Java that is compatible with your project

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Move to Android Directory
        run: cd android

      - name: Make Debug Build
        run: ./gradlew assembleDebug

      - name: Upload Debug Build
        uses: actions/upload-artifact@v2
        with:
          name: debug-build
          path: app/build/outputs/apk/debug/*.apk
