version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: |
          cd android
          ./gradlew build
      - name: Build Android JS Bundle
        run: |
          yarn run package-android
      - name: Delete Android build duplicate assets resource
        run: yarn run delete-pics
      - name: Install bundler
        run: |
          cd android
          gem install bundler
      - name: Install gem plugins
        run: |
          cd android
          bundle install
      - name: Run fastlane
        run: |
          cd android
          bundle exec fastlane build_qa
