name: Build Android Debug APK

on:
  push:
    branches:
      - main # Change this to your main branch name, if different
  # You can add more trigger events if needed, e.g., pull_request

jobs:
  build:
    runs-on: ubuntu-latest # You can change the runner as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17 # You can change the Java version if needed

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 20 # You can change the Node.js version if needed

      - name: Install Dependencies
        run: npm install
        working-directory: android-app # Change to your Android project directory

      - name: Build Android Debug APK
        run: ./gradlew assembleDebug
        working-directory: android-app # Change to your Android project directory

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: android-app/app/build/outputs/apk/debug/app-debug.apk
