version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0
      - image: cimg/android:2022.10
    environment:
      JVM_OPTS: -Xmx2048m
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm run test

      - run:
          name: Set up Java environment
          command: sudo apt-get install openjdk-11-jdk

      - run:
          name: Move to Android Directory
          command: cd android

      - restore_cache:
          key: gradle-cache-{{ checksum "gradle-wrapper.properties" }}

      - run:
          name: Make Debug Build
          command: ./gradlew assembleDebug

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "gradle-wrapper.properties" }}

      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: debug-apks
